spring:
  redis:
    host: 172.22.180.199 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/micro-auth/rsa/publicKey'   #通过micro-auth controller接口获取RSA的公钥
logging:
  level:
    root: info
    com.easy.micro: debug
logstash:
  host: 172.22.180.199