spring:
  datasource:
    url: jdbc:mysql://172.22.180.199:3306/micro?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  redis:
    host: 172.22.180.199 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
logging:
  level:
    root: info
    com.easy.micro: debug
logstash:
  host: 172.22.180.199