server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: micro-auth
          uri: lb://micro-auth
          predicates:
            - Path=/micro-auth/**
          filters:
            - StripPrefix=1
        - id: micro-admin
          uri: lb://micro-admin
          predicates:
            - Path=/micro-admin/**
          filters:
            - StripPrefix=1
        - id: micro-demo
          uri: lb://micro-demo
          predicates:
            - Path=/micro-demo/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/micro-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/micro-auth/oauth/token"
      - "/micro-auth/rsa/publicKey"
      - "/micro-admin/admin/login"
      - "/micro-admin/admin/register"
      - "/micro-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
